# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "devDeploy"
  - "stagDeploy"
  - "prodDeploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "RelationLab/relation-hasura-cache-eks"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  devPulumiOutputs:
    title: "Pulumi Outputs Dev"
    stage: devDeploy
    image: "pulumi/pulumi-nodejs:latest"
    working_directory: "${{clone}}"
    commands:
      - npm install
      - pulumi login
      - pulumi stack select dev
      - cf_export AWS_ECR_REPO_NAME=$(pulumi stack output ecrRepositoryName)
      - cf_export AWS_ECR_REPO_URL=$(pulumi stack output ecrRepositoryUrl)
      - cf_export HASURA_ENGINE_SECRET_ID_DEV=$(pulumi stack output hasuraEngineSecretId)
      - cf_export AWS_REDIS_CLUSTER_ENDPOINT_DEV=$(pulumi stack output redisClusterEndpoint)

  prepareArtifacts:
    type: "parallel"
    stage: devDeploy
    steps:
      buildAppImage:
        title: "Building App Docker image"
        stage: devDeploy
        type: "build"
        image_name: "${{AWS_ECR_REPO_NAME}}"
        working_directory: "${{clone}}/app"
        dockerfile: "Dockerfile"
        tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"

      fetchDevSecrets:
        title: "Fetch Dev AWS Secrets"
        type: aws-secrets-manager
        stage: devDeploy
        arguments:
          AWS_DEFAULT_REGION: "${{AWS_DEFAULT_REGION}}"
          secrets:
            - secret_arn: "${{HASURA_ENGINE_SECRET_ID_DEV}}"
              key: "hasuraAdminSecret"
              store_in: HASURA_ENGINE_ADMIN_SECRET_DEV

  devHelmInstall:
    title: "Deploy helm to AWS EKS dev env"
    type: helm
    stage: devDeploy
    working_directory: "${{clone}}"
    arguments:
      chart_name: helm
      release_name: hasura-cache
      helm_version: 3.9.0
      namespace: dev
      kube_context: wired-eks-prod
      custom_values:
        - "image_repository=${{AWS_ECR_REPO_URL}}"
        - "image_tag=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
        - "app_cacheDisabled=${{APP_CACHE_DISABLED}}"
        - "hasuraEngine_adminSecret=${{HASURA_ENGINE_ADMIN_SECRET_DEV}}"
        - "redisCluster_endpoint=${{AWS_REDIS_CLUSTER_ENDPOINT_DEV}}"

  askForStagPermission:
    type: pending-approval
    stage: stagDeploy
    title: Deploy to stagging?

  stagPulumiOutputs:
    title: "Pulumi Outputs Stag"
    image: "pulumi/pulumi-nodejs:latest"
    working_directory: "${{clone}}"
    stage: stagDeploy
    commands:
      - npm install
      - pulumi login
      - pulumi stack select stag
      - cf_export HASURA_ENGINE_SECRET_ID_STAG=$(pulumi stack output hasuraEngineSecretId)
      - cf_export AWS_REDIS_CLUSTER_ENDPOINT_STAG=$(pulumi stack output redisClusterEndpoint)

  stagFetchSecrets:
    title: "Fetch Stag AWS Secrets"
    type: aws-secrets-manager
    stage: stagDeploy
    arguments:
      AWS_DEFAULT_REGION: "${{AWS_DEFAULT_REGION}}"
      secrets:
        - secret_arn: "${{HASURA_ENGINE_SECRET_ID_STAG}}"
          key: "hasuraAdminSecret"
          store_in: HASURA_ENGINE_ADMIN_SECRET_STAG

  stagDeploy:
    title: "Deploy helm to AWS EKS stag env"
    stage: stagDeploy
    type: helm
    working_directory: "${{clone}}"
    arguments:
      chart_name: helm
      release_name: hasura-cache
      helm_version: 3.9.0
      namespace: stag
      kube_context: wired-eks-prod
      custom_values:
        - "image_repository=${{AWS_ECR_REPO_URL}}"
        - "image_tag=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
        - "app_cacheDisabled=${{APP_CACHE_DISABLED}}"
        - "hasuraEngine_adminSecret=${{HASURA_ENGINE_ADMIN_SECRET_STAG}}"
        - "redisCluster_endpoint=${{AWS_REDIS_CLUSTER_ENDPOINT_STAG}}"

  askForProdPermission:
    type: pending-approval
    stage: prodDeploy
    title: Deploy to production?

  prodPulumiOutputs:
    title: "Pulumi Outputs Prod"
    image: "pulumi/pulumi-nodejs:latest"
    working_directory: "${{clone}}"
    stage: prodDeploy
    commands:
      - npm install
      - pulumi login
      - pulumi stack select prod
      - cf_export HASURA_ENGINE_SECRET_ID_PROD=$(pulumi stack output hasuraEngineSecretId)
      - cf_export AWS_REDIS_CLUSTER_ENDPOINT_PROD=$(pulumi stack output redisClusterEndpoint)

  prodFetchSecrets:
    title: "Fetch Prod AWS Secrets"
    type: aws-secrets-manager
    stage: prodDeploy
    arguments:
      AWS_DEFAULT_REGION: "${{AWS_DEFAULT_REGION}}"
      secrets:
        - secret_arn: "${{HASURA_ENGINE_SECRET_ID_PROD}}"
          key: "hasuraAdminSecret"
          store_in: HASURA_ENGINE_ADMIN_SECRET_PROD

  prodDeploy:
    title: "Deploy helm to AWS EKS prod env"
    stage: prodDeploy
    type: helm
    working_directory: "${{clone}}"
    arguments:
      chart_name: helm
      release_name: hasura-cache
      helm_version: 3.9.0
      namespace: prod
      kube_context: wired-eks-prod
      custom_values:
        - "image_repository=${{AWS_ECR_REPO_URL}}"
        - "image_tag=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
        - "app_cacheDisabled=${{APP_CACHE_DISABLED}}"
        - "hasuraEngine_adminSecret=${{HASURA_ENGINE_ADMIN_SECRET_PROD}}"
        - "redisCluster_endpoint=${{AWS_REDIS_CLUSTER_ENDPOINT_PROD}}"
