# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "prodDeploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "RelationLab/relation-hasura-cache-eks"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  prodPulumiOutputs:
    title: "Pulumi Outputs Prod"
    image: "pulumi/pulumi-nodejs:latest"
    working_directory: "${{clone}}"
    stage: prodDeploy
    commands:
      - npm install
      - pulumi login
      - pulumi stack select prod
      - cf_export AWS_ECR_REPO_NAME=$(pulumi stack output ecrRepositoryName)
      - cf_export AWS_ECR_REPO_URL=$(pulumi stack output ecrRepositoryUrl)
      - cf_export HASURA_ENGINE_SECRET_ID_PROD=$(pulumi stack output hasuraEngineSecretId)
      - cf_export AWS_SERVICE_ACCOUNT_NAME_PROD=$(pulumi stack output awsServiceAccountName)
      - cf_export HASURA_ENGINE_SECRET_ID_PROD=$(pulumi stack output hasuraEngineSecretId)

  prodFetchSecrets:
    title: "Fetch Prod AWS Secrets"
    type: aws-secrets-manager
    stage: prodDeploy
    arguments:
      AWS_DEFAULT_REGION: "${{AWS_DEFAULT_REGION}}"
      secrets:
        - secret_arn: "${{HASURA_ENGINE_SECRET_ID_PROD}}"
          key: "hasuraAdminSecret"
          store_in: HASURA_ENGINE_ADMIN_SECRET_PROD

  prodDeploy:
    title: "Deploy helm to AWS EKS prod env"
    stage: prodDeploy
    type: helm
    working_directory: "${{clone}}"
    arguments:
      chart_name: helm
      release_name: hasura-cache
      helm_version: 3.9.0
      namespace: prod
      kube_context: wired-eks-prod
      custom_values:
        - "image_repository=${{AWS_ECR_REPO_URL}}"
        - "image_tag=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
        - "app_cacheDisabled=${{APP_CACHE_DISABLED}}"
        - "hasuraEngine_adminSecret=${{HASURA_ENGINE_ADMIN_SECRET_PROD}}"
        - "serviceAccount_name=${{AWS_SERVICE_ACCOUNT_NAME_PROD}}"
